theme: jekyll-theme-slate

title: Computernetzwerke - Herstellen einer Verbindung zu einer Website
subtitle: Studienleistung , Fachdidak5tik, 2 GymInf
description: ' ' 

includes_dir     : ./_includes
layouts_dir:  ./_layouts
plugins:
  - jemoji
